# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FoodPreferences.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FoodPreferences.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15\x46oodPreferences.proto\x12\x08protobuf\"D\n\nPersonFood\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x61voriteFood\x18\x02 \x01(\t\x12\x12\n\ntimesEaten\x18\x03 \x01(\x05\x62\x06proto3'
)




_PERSONFOOD = _descriptor.Descriptor(
  name='PersonFood',
  full_name='protobuf.PersonFood',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.PersonFood.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='favoriteFood', full_name='protobuf.PersonFood.favoriteFood', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timesEaten', full_name='protobuf.PersonFood.timesEaten', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['PersonFood'] = _PERSONFOOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonFood = _reflection.GeneratedProtocolMessageType('PersonFood', (_message.Message,), {
  'DESCRIPTOR' : _PERSONFOOD,
  '__module__' : 'FoodPreferences_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.PersonFood)
  })
_sym_db.RegisterMessage(PersonFood)


# @@protoc_insertion_point(module_scope)
